set nocompatible
filetype off
" installed plugins {{{
call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'altercation/vim-colors-solarized'
Plug 'Chiel92/vim-autoformat'
Plug 'chrisbra/SudoEdit.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'danro/rename.vim'
Plug 'easymotion/vim-easymotion'
Plug 'edkolev/tmuxline.vim'
Plug 'elzr/vim-json'
Plug 'ervandew/supertab'
Plug 'hail2u/vim-css3-syntax'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'jreybert/vimagit'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'kshenoy/vim-signature'
Plug 'majutsushi/tagbar'
Plug 'mattn/emmet-vim'
Plug 'mattn/webapi-vim'
Plug 'mbbill/undotree'
Plug 'mhinz/vim-startify'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'pangloss/vim-javascript'
Plug 'plasticboy/vim-markdown'
Plug 'rhysd/clever-f.vim'
Plug 'roxma/vim-paste-easy'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'Valloric/YouCompleteMe'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-scripts/matchit.zip'
Plug 'vim-scripts/YankRing.vim'
Plug 'vim-syntastic/syntastic'
call plug#end()
" }}}
set noerrorbells
set novisualbell
set t_vb=
set tm=500
set wildignore=*.o,*.class,*.pyc
set wildmenu
set ruler
set ignorecase
set smartcase
set hlsearch
set incsearch
let &colorcolumn="80,".join(range(100,999),",")
set nobackup
set lazyredraw
set cursorline
set nu
set magic
set showmatch
set mat=2
set backspace=2
set ffs=unix,dos,mac
set grepprg=rg\ --vimgrep
" cache settings {{{
set backupdir=~/.vimfile/backup//
set directory=~/.vimfile/swap//
set undodir=~/.vimfile/undo//
set noswapfile
" }}}
" encoding {{{
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,big5,gb2312,latin1
" }}}
syntax on
if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif
if has('gui_running')
  set t_Co=256
  set background=light
else
  set background=dark
endif
" Tab Setting {
set smarttab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
inoremap <S-Tab> <C-V><Tab>
" }
set autoindent
set smartindent
set wrap
set list
set listchars=tab:→\ ,trail:·,nbsp:¬,precedes:«,extends:»
set laststatus=2

" custom mappings {{{
let mapleader=" "
let g:mapleader=" "
noremap 0 ^
noremap ^ 0
" visual up/down move
nnoremap j gj
nnoremap k gk
" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
" shift between tabs
map <S-H> gT
map <S-L> gt
noremap <Leader>w :w<CR>
" redraw
noremap <leader>r :redraw!<CR>
" }}}

" filetype settings {{{
au BufNewFile,BufRead Dockerfile.* set filetype=dockerfile
au FileType Makefile set noexpandtab
au FileType python set shiftwidth=2 tabstop=2 softtabstop=2 expandtab
au FileType sh set shiftwidth=2 tabstop=2 softtabstop=2 expandtab
au FileType c,cpp set shiftwidth=8 tabstop=8 softtabstop=8
" }}}

" airblade/vim-gitgutter {{{
nmap ]h <Plug>GitGutterNextHunk
nmap [h <Plug>GitGutterPrevHunk
nmap <Leader>gt :GitGutterToggle<CR>
nmap <Leader>ga <Plug>GitGutterStageHunk
nmap <Leader>gr <Plug>GitGutterUndoHunk
" }}}

" altercation/vim-colors-solarized {{{
let g:solarized_visibility = 'default'
let g:solarized_termcolors = 256
colorscheme solarized
hi cursorline ctermbg=235
hi colorcolumn ctermbg=236
" }}}

" Chiel92/vim-autoformat {{{
let g:formatdef_yapf = "'yapf --style=\"{based_on_style:chromium,indent_width:'.&shiftwidth.(&textwidth ? ',column_limit:'.&textwidth : '').',ALLOW_MULTILINE_LAMBDAS: true, I18N_FUNCTION_CALL: func_not__exist}\" -l '.a:firstline.'-'.a:lastline"
let g:formatters_python=['yapf']
let g:formatters_javascript=['clangformat']
let g:autoformat_autoindent=0
let g:autoformat_retab=0
let g:autoformat_remove_trailing_spaces=0
noremap <Leader>a :Autoformat<CR>
" }}}

" chrisbra/SudoEdit.vim {{{
" }}}

" christoomey/vim-tmux-navigator {{{
" }}}

" easymotion/vim-easymotion {{{
let g:EasyMotion_keys = 'asdghklqwertyuiopzxcvbnmfjop'
let g:EasyMotion_do_mapping = 0 " Disable default mappings
let g:EasyMotion_smartcase = 1
nmap s <Plug>(easymotion-overwin-f2)
map  <Leader>/ <Plug>(easymotion-sn)
omap <Leader>/ <Plug>(easymotion-tn)
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)
" }}}

" edkolev/tmuxline.vim {{{
let g:tmuxline_powerline_separators = 1
" :TmuxlineSnapShot [file] "For tmux to source a snapshot file
" }}}

" elzr/vim-json {{{
let g:vim_json_syntax_conceal = 0
" }}}

" jistr/vim-nerdtree-tabs {{{
let g:nerdtree_tabs_open_on_new_tab = 0
let g:nerdtree_tabs_synchronize_view = 1
" }}}

" junegunn/fzf, junegunn/fzf'.vim {{{
let g:fzf_history_dir = '~/.local/share/fzf-history'
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Statement'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'ToDo'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
command! -bang -nargs=* Rl call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --smart-case --hidden --follow --color "always" '.shellescape(<q-args>).'| tr -d "\017"', 1, <bang>0)
command! -bang -nargs=* R call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --smart-case --hidden --color "always" '.shellescape(<q-args>).'| tr -d "\017"', 1, <bang>0)
noremap <leader>p :Files<CR>
noremap <leader>o :Buffers<CR>
noremap <leader>f :Lines<CR>
noremap <leader><leader> :BLines<CR>
noremap <leader>t :Tags<CR>
" }}}

" kshenoy/vim-signature {{{
let g:SignatureMarkTextHLDynamic = 1
let g:SignatureMarkerTextHLDynamic = 1
" }}}

" majutsushi/tagbar {{{
nnoremap <silent><S-Tab> :TagbarToggle<CR>
" }}}

" mattn/emmet-vim {{{
" }}}

" mbbill/undotree {{{
nnoremap <silent><leader>u :UndotreeToggle<cr>
" }}}

" nathanaelkane/vim-indent-guides {{{
let g:indent_guides_auto_colors=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=234 "system bg color
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=235
" }}}

" rhysd/clever-f.vim {{{
" }}}

" octol/vim-cpp-enhanced-highlight {{{
let g:cpp_class_scope_highlight = 1
"let g:cpp_experimental_template_highlight = 1
let g:cpp_experimental_simple_template_highlight = 1
let g:cpp_concepts_highlight = 1
" }}}

"scrooloose/nerdcommenter {{{
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDAltDelims_java = 1
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
"}}}

" terryma/vim-multiple-cursors {{{
let g:multi_cursor_use_default_mapping=0
" }}}

" Valloric/YouCompleteMe {{{
let g:ycm_python_binary_path = 'python'
let g:ycm_complete_in_strings = 1
let g:ycm_min_num_of_chars_for_completion=2
let g:ycm_goto_buffer_command='new-or-existing-tab'
let g:ycm_key_list_previous_completion = ['<Up>']
noremap gd :YcmCompleter GoTo<CR>
" }}}

" vim-airline/vim-airline {{{
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
" }}}

" vim-airline/airline_themes {{{
let g:airline_theme = 'light'
" }}}

" vim-syntastic/syntastic {{{
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'
let g:syntastic_python_pylint_args = '--rcfile=~/.pylintrc'
nnoremap <silent> <F7> :SyntasticToggleMode<CR>
" }}}

" ChromeOS settings {{{
let g:localrc_project_root = '~/cros/src/platform/factory'
call localrc#load()
" }}}
